### ISSUE TITLE
API proposals

### ISSUE THREAD

**Issue by tkazec** [gameclosure/ff#21]
Currently ff's API feels kinda "in between". Here's my proposal for the next major version:

* `f#slot([n = 1])`
* `f#slotPlain([n = 1])`

Usage comparison:

* `f#slot()`, `f#slotPlain()`, and `f#slotPlain(n)` stay the same
* `f#slot(args...)` becomes `f#pass(args...)`
* `f#slotMulti(n)` becomes `f#slot(n)`
* `f#wait()` becomes `f#slot(0)`
* `f#waitPlain()` becomes `f#slotPlain(0)`

Thoughts?

**Comment by charlesfeng** [comment]
whoa
